### ISSUE TITLE
Modales des activités

### ISSUE THREAD

**Issue by thomasgall67** [nd4pa/b3t#23]
La modale affiche 
* le Titre de l'activité
* l'icone de l'état
* Une courte description
     * Pending : "Ton activité est en cours de validation par un chef ou une cheftaine
     * Valdiated : "Ton activité a été validée ! Bravo à toi !"
     * Refused : "Ton activité n'a pas été validée mais tu as la possibilité de la refaire"
* Pour Validated et Refused : un commentaire
* Un bouton OK ==> Retour sur la page du progression personnelle
* Pour Refused : Bouton réessayer ==> Retour sur la page activité

![08a_Progression personnelle – Mod Pending](https://user-images.githubusercontent.com/62614774/77564332-d84f2e00-6ec2-11ea-9a7b-339d7c0ef116.png)
![08b_Progression personnelle – Mod Validate](https://user-images.githubusercontent.com/62614774/77564334-d8e7c480-6ec2-11ea-9f3e-bd6ef923da7f.png)
![08c_Progression personnelle – Mod Refused](https://user-images.githubusercontent.com/62614774/77564335-d9805b00-6ec2-11ea-9000-122db1e9b340.png)

**Comment by guiyom-e** [comment]
est-ce qu'on a prévu le cas d'une activité non terminée ("INPROGRESS") ?
