### ISSUE TITLE
Configuration de la Police

### ISSUE THREAD

**Issue by thomasgall67** [nd4pa/b3t#7]
Intégrer en police :
**Texte général** : Sarabun `<link href="https://fonts.googleapis.com/css?family=Sarabun&display=swap" rel="stylesheet">`

**Titres** : Caveat Brush `<link href="https://fonts.googleapis.com/css?family=Caveat+Brush&display=swap" rel="stylesheet">`

**Comment by guiyom-e** [comment]
J'ai ajouté ces polices dans `main.css` (#35 )
