### ISSUE TITLE
Intégration des couleurs

### ISSUE THREAD

**Issue by thomasgall67** [nd4pa/b3t#8]
Couleurs pour le site :

* Header : `#0077b3`
* Textes (default) : `#003a5d`
* Parcours Bosses et Bobos: `#ff8300`
* Parcours 3 Etoiles : `#d03f15`
* Parcours Ces'Arts : `#6e74aa`
* Parcours Robinson : `#007254`

* Success :  `#007254`
* Danger : `#d03f15`
* Default : `#003a5d`

**Comment by guiyom-e** [comment]
J'ai ajouté ces polices dans `main.css` (#35 )
